theme: jekyll-theme-cayman
title: Patrick Stuchlik
email: pat@pat.fyi
description: Welcome to my website.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://pat.fyi # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PatrickStuchlik
github_username:  patrickstuchlik
